### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ThatOneCalculator** [surrealdb/echodb#1]
Having documentation on how to actually use EchoDB would be useful

**Comment by guycipher** [comment]
and tests.

**Comment by tobiemh** [comment]
This situation should now be improved with commit https://github.com/surrealdb/echodb/commit/dfce56c52f9e0d426e23c3fee79eba6db216b43e.

Documentation is now visible at https://docs.rs/echodb/latest/echodb/ 🎉 🚀
